import Link from "next/link";
import { notFound } from "next/navigation";
import { getServerSession } from "next-auth";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Tabs } from "@/components/ui/tabs";
import { TeacherMode } from "@/components/teacher-mode";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function TopicPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const session = await getServerSession(authOptions);
  const userId = session?.user.id as string;
  const topic = await prisma.topic.findUnique({
    where: { slug },
    include: {
      problems: { orderBy: [{ difficulty: "asc" }, { title: "asc" }] },
      quizzes: true,
      progress: { where: { userId } }
    }
  });

  if (!topic) notFound();

  const progress = topic.progress[0];

  return (
    <div className="space-y-5">
      <Button variant="ghost" asChild>
        <Link href="/roadmap">
          <ArrowLeft className="h-4 w-4" />
          Roadmap
        </Link>
      </Button>

      <section className="grid gap-4 xl:grid-cols-[1.3fr_0.7fr]">
        <Card>
          <CardHeader>
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant="outline">Step {topic.sortOrder}</Badge>
              <Badge>{topic.problems.length} practice problems</Badge>
            </div>
            <CardTitle className="text-2xl">{topic.title}</CardTitle>
            <CardDescription>{topic.description}</CardDescription>
          </CardHeader>
          <CardContent>
            <Tabs
              tabs={[
                {
                  value: "theory",
                  label: "Theory",
                  content: <p className="whitespace-pre-line leading-7 text-muted-foreground">{topic.theory}</p>
                },
                {
                  value: "notes",
                  label: "Notes",
                  content: <p className="whitespace-pre-line leading-7 text-muted-foreground">{topic.notes}</p>
                },
                {
                  value: "visual",
                  label: "Visual",
                  content: <p className="whitespace-pre-line leading-7 text-muted-foreground">{topic.visualGuide}</p>
                },
                {
                  value: "mistakes",
                  label: "Mistakes",
                  content: (
                    <ul className="list-disc space-y-2 pl-5 text-muted-foreground">
                      {topic.commonMistakes.map((mistake) => (
                        <li key={mistake}>{mistake}</li>
                      ))}
                    </ul>
                  )
                }
              ]}
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Progress</CardTitle>
            <CardDescription>Completion and accuracy for this topic.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div>
              <div className="mb-2 flex justify-between text-sm">
                <span className="text-muted-foreground">Completion</span>
                <span className="font-medium">{Math.round(progress?.completion ?? 0)}%</span>
              </div>
              <Progress value={progress?.completion ?? 0} />
            </div>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div className="rounded-md bg-muted p-3">
                <p className="text-muted-foreground">Solved</p>
                <p className="text-xl font-semibold">{progress?.problemsSolved ?? 0}</p>
              </div>
              <div className="rounded-md bg-muted p-3">
                <p className="text-muted-foreground">Accuracy</p>
                <p className="text-xl font-semibold">{Math.round(progress?.accuracy ?? 0)}%</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>

      <TeacherMode slug={topic.slug} />

      <section className="grid gap-4 xl:grid-cols-[1fr_0.8fr]">
        <Card>
          <CardHeader>
            <CardTitle>Practice Problems</CardTitle>
            <CardDescription>Problems seeded for this topic and generated by AI.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {topic.problems.map((problem) => (
              <Link key={problem.id} href={`/problems/${problem.slug}`} className="flex items-center justify-between rounded-md border p-3 transition-colors hover:bg-muted">
                <div>
                  <p className="font-medium">{problem.title}</p>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {problem.tags.slice(0, 3).map((tag) => (
                      <Badge key={tag} variant="secondary">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                </div>
                <Badge variant={problem.difficulty === "EASY" ? "easy" : problem.difficulty === "MEDIUM" ? "medium" : "hard"}>
                  {problem.difficulty}
                </Badge>
              </Link>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Quizzes</CardTitle>
            <CardDescription>Quick checks before coding.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {topic.quizzes.map((quiz) => (
              <div key={quiz.id} className="rounded-md border p-4">
                <p className="font-medium">{quiz.question}</p>
                <div className="mt-3 space-y-2">
                  {(quiz.options as string[]).map((option) => (
                    <div key={option} className="flex items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm">
                      {option === quiz.answer ? <CheckCircle2 className="h-4 w-4 text-primary" /> : <span className="h-4 w-4 rounded-full border" />}
                      {option}
                    </div>
                  ))}
                </div>
                <p className="mt-3 text-sm text-muted-foreground">{quiz.explanation}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      </section>
    </div>
  );
}
